apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-storage
              mountPath: /root/.ollama
      initContainers:
        - name: init-ollama
          image: ollama/ollama
          command: ['sh', '-c']
          args:
            - |
              ollama serve & sleep 20;
              ollama pull $MODEL_NAME;
          env:
            - name: MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: ollama-config
                  key: modelName
          volumeMounts:
            - name: ollama-storage
              mountPath: /root/.ollama
      
      volumes:
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: ollama-pvc