services:

  ollama:
    image: ollama/ollama
    container_name: ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama:/root/.ollama

  chat:
    image: amitgiri13/ollama-chat:1.0.0
    container_name: ollama-chat

    ports:
      - "8000:8000"

    environment:
      - OLLAMA_URL=http://ollama:11434

    depends_on:
      - ollama

volumes:
  ollama: